# Generated by Django 5.1.2 on 2024-10-30 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='goods',
            table='goods',
        ),
    ]
